/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.proyectofinal.Interfaz;

import com.mycompany.proyectofinal.Ventas.GestorDeVentas;
import com.mycompany.proyectofinal.Ventas.Vaso;
import java.util.ArrayList;

/**
 *
 * @author developerweb
 */
public class EditarVasoVentasDialog extends javax.swing.JDialog {

    private PedidoTemporalDialog parent;
    private GestorDeVentas gestor;
    String parametro;
    String nuevo;
    String nVaso;
    public EditarVasoVentasDialog(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxParametro = new javax.swing.JComboBox<>();
        comboBoxNVaso = new javax.swing.JComboBox<>();
        comboBoxNParametro = new javax.swing.JComboBox<>();
        seleccioneParametroLabel = new javax.swing.JLabel();
        seleccioneNVasoLabel = new javax.swing.JLabel();
        mostrarParametroLabel = new javax.swing.JLabel();
        mostrarParametro = new javax.swing.JLabel();
        seleccioneParametroNuevoLabel = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        comboBoxParametro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione el parametro a editar--", "Tamaño", "Base", "Tipo Boba", "Sabor 1", "Sabor 2" }));
        comboBoxParametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxParametroActionPerformed(evt);
            }
        });

        comboBoxNVaso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione el Nro de Vaso--" }));
        comboBoxNVaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxNVasoActionPerformed(evt);
            }
        });

        comboBoxNParametro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione el parametro nuevo--" }));
        comboBoxNParametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxNParametroActionPerformed(evt);
            }
        });

        seleccioneParametroLabel.setText("Seleccione el parametro a editar");

        seleccioneNVasoLabel.setText("Ingrese el numero de vaso");

        mostrarParametroLabel.setText("Parametro actual");

        mostrarParametro.setText("--------");

        seleccioneParametroNuevoLabel.setText("Seleccione el parametro nuevo");

        editButton.setText("EDITAR");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seleccioneParametroLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboBoxParametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seleccioneParametroNuevoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboBoxNParametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seleccioneNVasoLabel)
                                    .addComponent(mostrarParametroLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(comboBoxNVaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(mostrarParametro)
                                        .addGap(99, 99, 99))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(editButton)))
                .addGap(0, 4, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxParametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seleccioneParametroLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxNVaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seleccioneNVasoLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mostrarParametro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mostrarParametroLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxNParametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seleccioneParametroNuevoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(editButton)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxParametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxParametroActionPerformed
        parametro = comboBoxParametro.getSelectedItem().toString();
        agregarOpcionesComboBox(parametro);
    }//GEN-LAST:event_comboBoxParametroActionPerformed

    private void comboBoxNVasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxNVasoActionPerformed
        nVaso = comboBoxNVaso.getSelectedItem().toString();
        parametro = comboBoxParametro.getSelectedItem().toString();
        mostrarParametro(nVaso,parametro);
    }//GEN-LAST:event_comboBoxNVasoActionPerformed

    private void comboBoxNParametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxNParametroActionPerformed
        nuevo = comboBoxNParametro.getSelectedItem().toString();
    }//GEN-LAST:event_comboBoxNParametroActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        gestor.editarInfoVaso(nVaso, nuevo, parametro);
        parent.actualizarTablaEditar(nVaso, nuevo, parametro);
        mostrarParametro(nVaso,parametro);
    }//GEN-LAST:event_editButtonActionPerformed
    
    public void agregarNumerosComboBox() {
        ArrayList<Vaso> vasos=gestor.getPedidoTemporal().getVasos();
        comboBoxNVaso.addItem("--Seleccione el numero de vaso--");
        for(int i=0;i<vasos.size();i++){
            comboBoxNVaso.addItem(i+1+"");
        }
    }
    
    public void editarvaso(GestorDeVentas gestor, PedidoTemporalDialog aThis) {
       parent=aThis;
       this.gestor=gestor;
    }
    private void mostrarParametro(String nVaso,String parametro) {
       String actual = null;
       ArrayList<Vaso> vasos=gestor.getPedidoTemporal().getVasos();
       switch (parametro) {
           case "Tamaño" -> actual = vasos.get(Integer.parseInt(nVaso)-1).getTamVaso();
           case "Base" -> actual = vasos.get(Integer.parseInt(nVaso)-1).getBase();
           case "Tipo Boba" -> actual = vasos.get(Integer.parseInt(nVaso)-1).getTipoBoba();
           case "Sabor 1" -> actual = vasos.get(Integer.parseInt(nVaso)-1).getSabor1();
           case "Sabor 2" -> actual = vasos.get(Integer.parseInt(nVaso)-1).getSabor2();
           default -> vasos.get(Integer.parseInt(nVaso)-1).getTamVaso();
       }
       mostrarParametro.setText(actual);
    }
    private void agregarOpcionesComboBox(String antiguo) {
       switch (antiguo) {
           case "Tamaño" ->comboBoxNParametro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione sabor--", "Grande","Mediano" }));
           case "Base" -> comboBoxNParametro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione sabor--", "Agua","Leche" }));
           case "Tipo Boba" -> comboBoxNParametro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione sabor--", "Regular","Explosivo" }));
           case "Sabor 1" ->  comboBoxNParametro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione sabor--", "Chocolate",
                              "Oreo", "Limon", "Maracuya"}));
           case "Sabor 2" -> comboBoxNParametro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione sabor--", "Chocolate",
                              "Oreo", "Limon", "Maracuya", "Ninguno" }));
       }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarVasoVentasDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarVasoVentasDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarVasoVentasDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarVasoVentasDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditarVasoVentasDialog dialog = new EditarVasoVentasDialog(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxNParametro;
    private javax.swing.JComboBox<String> comboBoxNVaso;
    private javax.swing.JComboBox<String> comboBoxParametro;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel mostrarParametro;
    private javax.swing.JLabel mostrarParametroLabel;
    private javax.swing.JLabel seleccioneNVasoLabel;
    private javax.swing.JLabel seleccioneParametroLabel;
    private javax.swing.JLabel seleccioneParametroNuevoLabel;
    // End of variables declaration//GEN-END:variables

}
