/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.proyectofinal.Interfaz;

import com.mycompany.proyectofinal.Ventas.GestorDeVentas;
import com.mycompany.proyectofinal.Ventas.Pedido;
import com.mycompany.proyectofinal.Ventas.Vaso;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author developerweb
 */
public class PedidoTemporalDialog extends javax.swing.JDialog {
    private MenuVentas parent;
    private GestorDeVentas gestor;
    private DefaultTableModel dtm;
    private Object [] o = new Object[6];
    /**
     * Creates new form PedidoTemporalDialog
     */
    public PedidoTemporalDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dtm=(DefaultTableModel)TablaPedidoTemporal.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClienteTempLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NroPedidoLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        confirmarPedidoButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPedidoTemporal = new javax.swing.JTable();
        editarVasoButton = new javax.swing.JButton();
        eliminarVasoButon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ClienteTempLabel.setText("Cliente");

        jLabel3.setText("jLabel3");

        NroPedidoLabel.setText("NroPedido");

        jLabel5.setText("jLabel5");

        confirmarPedidoButton.setText("CONFIRMAR PEDIDO");
        confirmarPedidoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarPedidoButtonActionPerformed(evt);
            }
        });

        TablaPedidoTemporal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro Vaso", "Tamaño", "Base", "Tipo Boba", "Sabor1", "Sabor2"
            }
        ));
        jScrollPane1.setViewportView(TablaPedidoTemporal);

        editarVasoButton.setText("Editar Vaso");
        editarVasoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarVasoButtonActionPerformed(evt);
            }
        });

        eliminarVasoButon.setText("Eliminar Vaso");
        eliminarVasoButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarVasoButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NroPedidoLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ClienteTempLabel)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eliminarVasoButon)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(editarVasoButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(confirmarPedidoButton)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClienteTempLabel)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NroPedidoLabel)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eliminarVasoButon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editarVasoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmarPedidoButton)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarVasoButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarVasoButonActionPerformed
        EliminarVasoDialog eli;
        eli = new EliminarVasoDialog(this,true);
        eli.setLocationRelativeTo(this);
        eli.eliminarVaso(gestor,this);
        eli.setVisible(true);
    }//GEN-LAST:event_eliminarVasoButonActionPerformed

    private void editarVasoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarVasoButtonActionPerformed
       EditarVasoDialog edi;
       edi = new EditarVasoDialog(this,true);
       edi.setLocationRelativeTo(this);
       edi.editarvaso(gestor,this);
       edi.agregarNumerosComboBox();
       edi.setVisible(true);
    }//GEN-LAST:event_editarVasoButtonActionPerformed

    private void confirmarPedidoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarPedidoButtonActionPerformed
        Pedido pedidoConfirmado=gestor.getPedidoTemporal();
        if (pedidoConfirmado.getVasos().isEmpty()){
           JOptionPane.showMessageDialog(
            null,
            "Confirmando un pedido sin vasos",
            "Error",
            JOptionPane.WARNING_MESSAGE
            );
           return;
       }else{
          gestor.confirmarPedido();
          parent.llenarColaDePedidos(pedidoConfirmado);
          dtm.setRowCount(0);
       }
    }//GEN-LAST:event_confirmarPedidoButtonActionPerformed
    public void setMensaje(String mensaje,String parametro){
        if(parametro.equals("cliente")){
            jLabel3.setText(mensaje);
        }else{
            jLabel5.setText(mensaje);
        }
    }
    public void agregarVasoATabla(Vaso vaso){
        o[0]=vaso.getNumVaso();
        o[1]=vaso.getTamVaso();
        o[2]=vaso.getBase();
        o[3]=vaso.getTipoBoba();
        o[4]=vaso.getSabor1();
        o[5]=vaso.getSabor2();
        dtm.addRow(o);
    }
    public void mandarGestorParent(GestorDeVentas gestor,MenuVentas parent) {
        this.gestor=gestor;
        this.parent=parent;
    }
    void actualizarTablaEliminar(String eliminado) {
        int indicedel=Integer.parseInt(eliminado)-1;
        dtm.removeRow(indicedel);
        if(dtm.getRowCount()>=1){
           for(int i=indicedel;i<dtm.getRowCount();i++){
              dtm.setValueAt(Integer.valueOf(gestor.getPedidoTemporal().getVasos().get(i).getNumVaso()), i, 0);
           } 
        }
    }
    void actualizarTablaEditar(String nVaso,String nuevo,String parametro) {
        int columnaedit;
        int filaedit=Integer.parseInt(nVaso)-1;
        switch (parametro) {
           case "Tamaño" -> columnaedit=1;
           case "Base" -> columnaedit=2;
           case "Tipo Boba" -> columnaedit=3;
           case "Sabor 1" -> columnaedit=4;
           case "Sabor 2" -> columnaedit=5;
           default -> columnaedit=1;
       }
        dtm.setValueAt(nuevo, filaedit, columnaedit);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedidoTemporalDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedidoTemporalDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedidoTemporalDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedidoTemporalDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PedidoTemporalDialog dialog = new PedidoTemporalDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClienteTempLabel;
    private javax.swing.JLabel NroPedidoLabel;
    private javax.swing.JTable TablaPedidoTemporal;
    private javax.swing.JButton confirmarPedidoButton;
    private javax.swing.JButton editarVasoButton;
    private javax.swing.JButton eliminarVasoButon;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables




}
