/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal.Interfaz;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Camila
 */
public class Provedor extends javax.swing.JFrame {

    /**
     * Creates new form Provedor
     */
    public Provedor() {
        initComponents();
        tablita.setModel(new DefaultTableModel(
        new Object[][] {}, // Lista vacía para evitar filas por defecto
        new String[] {"Nombre", "Teléfono", "Dirección"}
    ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablita = new javax.swing.JTable();
        agregarProv = new javax.swing.JButton();
        eliminarProv = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Telefono", "Direccion"
            }
        ));
        tablita.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tablita);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        agregarProv.setText("Agregar");
        agregarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProvActionPerformed(evt);
            }
        });
        getContentPane().add(agregarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, 120, 40));

        eliminarProv.setText("Eliminar");
        eliminarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProvActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, 130, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Proveedor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 140, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProvActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tablita.getModel();

        // Pedir al usuario que ingrese el nombre, teléfono y dirección
        String nombre = JOptionPane.showInputDialog("Ingrese el nombre del proveedor:");
        String telefono = JOptionPane.showInputDialog("Ingrese el teléfono del proveedor:");
        String direccion = JOptionPane.showInputDialog("Ingrese la dirección del proveedor:");

        // Agregar una nueva fila con los datos ingresados
        if (nombre != null && telefono != null && direccion != null) {
            model.addRow(new Object[]{nombre, telefono, direccion});
        }
    }//GEN-LAST:event_agregarProvActionPerformed

    private void eliminarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProvActionPerformed
        int selectedRow = tablita.getSelectedRow();

    // Verificar que haya una fila seleccionada
    if (selectedRow >= 0) {
        // Mostrar cuadro de confirmación
        int confirm = JOptionPane.showConfirmDialog(this, 
                "¿Estás seguro de que deseas eliminar este proveedor?", 
                "Confirmar eliminación", 
                JOptionPane.YES_NO_OPTION);

        // Si el usuario selecciona "Sí", eliminar la fila
        if (confirm == JOptionPane.YES_OPTION) {
            DefaultTableModel model = (DefaultTableModel) tablita.getModel();
            model.removeRow(selectedRow);
        }
    } else {
        // Mostrar mensaje si no se ha seleccionado ninguna fila
        JOptionPane.showMessageDialog(this, "Selecciona un proveedor para eliminar.");
    }
    }//GEN-LAST:event_eliminarProvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Provedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Provedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Provedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Provedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Provedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarProv;
    private javax.swing.JButton eliminarProv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablita;
    // End of variables declaration//GEN-END:variables
}
